[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["assets/tracks/**"]   # <— wichtig für Downloads

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
